CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_MODBUS=y
CONFIG_MODBUS_ROLE_SERVER=y
CONFIG_UI_MODBUS_RTU=y

CONFIG_VC_RUNTIME=y
CONFIG_VC_CHANNEL_CONTROLLER=y

CONFIG_ADC=y
CONFIG_DAC=y
CONFIG_SPI=y
CONFIG_HVB_VC_CHANNEL=y
CONFIG_AD5541=y
CONFIG_ADS1232=y

CONFIG_VC_SETTINGS_PERSISTENCE=y

CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_SHT3XD=y
CONFIG_SYS_STATUS=y
